@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
skinparam wrapWidth 300
skinparam linetype polyline
LAYOUT_LANDSCAPE()

Person(client, "Пользователь VR")
Person(operator, "Оператор")

System_Boundary(messenger, "Система потоковой передачи медиа-данных") {
    Container(vr_client, "VR клиент", "Игровой движок", "Компонент для запуска трансляции")
    Container(browser_client, "Браузерный клиент", "javascript", "Веб-страница для просмотра трансляции")
    Container(conn_service, "Сервис соединений", "golang", "Сервис для обмена данными, необходимыми для установки соединения")
}

System_Ext(monitoring, "Система мониторинга", "")

Rel(client, vr_client, "", "GUI")
Rel(operator, browser_client, "", "GUI")

Rel(vr_client, conn_service, "", "HTTP")
Rel(browser_client, conn_service, "", "HTTP")

Rel_U(browser_client, vr_client, "", "WebRTC")

Rel_L(monitoring, conn_service, "", "HTTP")

@enduml